"""empty message

Revision ID: 164d25bce1c2
Revises: ea2a6e99f218
Create Date: 2017-08-31 13:42:54.975817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '164d25bce1c2'
down_revision = 'ea2a6e99f218'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
