"""added first and last name to users table

Revision ID: 981f2ef707b0
Revises: b12ec0d6f93d
Create Date: 2017-05-18 11:58:28.739514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '981f2ef707b0'
down_revision = 'b12ec0d6f93d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
