"""empty message

Revision ID: 30920a53180d
Revises: 283ea58e9547
Create Date: 2017-08-27 07:59:35.046962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30920a53180d'
down_revision = '283ea58e9547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
