"""adding rating column

Revision ID: 144b49d42899
Revises: 11cf88327c38
Create Date: 2017-11-28 15:27:37.943533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '144b49d42899'
down_revision = '11cf88327c38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snacks', sa.Column('rating', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snacks', 'rating')
    # ### end Alembic commands ###
