"""added tasty

Revision ID: 1b24143fc731
Revises: 
Create Date: 2017-08-18 15:49:43.101072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b24143fc731'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('more-snacks', sa.Column('tasty', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('more-snacks', 'tasty')
    # ### end Alembic commands ###
