"""adding tastes_good column



Revision ID: 84d3aa50896d
Revises: 
Create Date: 2017-08-18 15:27:06.760199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84d3aa50896d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snacks', sa.Column('tastes_good', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snacks', 'tastes_good')
    # ### end Alembic commands ###
