"""add Price column

Revision ID: 90eec3574394
Revises: 
Create Date: 2017-08-18 16:05:45.958670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90eec3574394'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snack', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snack', 'price')
    # ### end Alembic commands ###
