"""empty message

Revision ID: b6adf90d0ae8
Revises: daf74a0e59ba
Create Date: 2017-02-10 13:34:48.836265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6adf90d0ae8'
down_revision = 'daf74a0e59ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snacks', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snacks', 'rating')
    # ### end Alembic commands ###
