"""added tastiness

Revision ID: c46b50ceb154
Revises: 9ecfcfd901b0
Create Date: 2017-11-28 16:18:55.829281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c46b50ceb154'
down_revision = '9ecfcfd901b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snacks', sa.Column('tastiness', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snacks', 'tastiness')
    # ### end Alembic commands ###
