"""empty message

Revision ID: da31fdc069ac
Revises: 0d57e0e2c4c9
Create Date: 2017-08-18 15:48:37.894906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da31fdc069ac'
down_revision = '0d57e0e2c4c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snacks', sa.Column('is_good', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snacks', 'is_good')
    # ### end Alembic commands ###
