"""empty message

Revision ID: 13800f89f77a
Revises: e65005b5fd2c
Create Date: 2017-02-16 17:11:40.599271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13800f89f77a'
down_revision = 'e65005b5fd2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_favorites',
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], )
    )
    op.drop_table('employees_messages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees_messages',
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='employees_messages_employee_id_fkey'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name='employees_messages_message_id_fkey')
    )
    op.drop_table('employee_favorites')
    # ### end Alembic commands ###
