"""empty message

Revision ID: 286273dadbc5
Revises: 4a9412a53ef4
Create Date: 2017-02-15 16:38:01.952449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '286273dadbc5'
down_revision = '4a9412a53ef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('password', sa.Text(), nullable=True))
    op.add_column('employees', sa.Column('username', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'employees', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_column('employees', 'username')
    op.drop_column('employees', 'password')
    # ### end Alembic commands ###
