"""empty message

Revision ID: 96f9e545ebc8
Revises: 13800f89f77a
Create Date: 2017-02-17 11:55:04.314834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96f9e545ebc8'
down_revision = '13800f89f77a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'messages', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'employee_id')
    # ### end Alembic commands ###
