"""add many to many relationship with messages-tags

Revision ID: a35b193c677c
Revises: 6f4cab9be9f4
Create Date: 2017-12-05 17:26:14.653681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a35b193c677c'
down_revision = '6f4cab9be9f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('messages_id', sa.Integer(), nullable=True),
    sa.Column('tags_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['messages_id'], ['messages.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['tags_id'], ['tags.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages_tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
