"""empty message

Revision ID: 650810452552
Revises: 9b205fcc8103
Create Date: 2017-02-13 14:48:35.708592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '650810452552'
down_revision = '9b205fcc8103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='message_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='message_pkey')
    )
    op.drop_table('messages')
    # ### end Alembic commands ###
