"""empty message

Revision ID: 288fe6dda3b6
Revises: de5d40633864
Create Date: 2017-08-31 17:01:20.661761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '288fe6dda3b6'
down_revision = 'de5d40633864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
