"""Add password and username

Revision ID: 679a839ba586
Revises: a35b193c677c
Create Date: 2017-12-06 20:20:20.059722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '679a839ba586'
down_revision = 'a35b193c677c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('username', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'username')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
