"""changing history table

Revision ID: 2ffa4b75b035
Revises: 91076b96b601
Create Date: 2017-05-22 15:24:33.813666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ffa4b75b035'
down_revision = '91076b96b601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('histories', sa.Column('city_lived_in', sa.Text(), nullable=True))
    op.drop_column('histories', 'birth_city')
    op.drop_column('histories', 'birth_year')
    op.drop_column('histories', 'birth_state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('histories', sa.Column('birth_state', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('histories', sa.Column('birth_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('histories', sa.Column('birth_city', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('histories', 'city_lived_in')
    # ### end Alembic commands ###
