"""adding relationship between resources

Revision ID: 60af6e745f16
Revises: 2ffa4b75b035
Create Date: 2017-05-22 15:45:12.609330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60af6e745f16'
down_revision = '2ffa4b75b035'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('histories', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'histories', 'owners', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'histories', type_='foreignkey')
    op.drop_column('histories', 'owner_id')
    # ### end Alembic commands ###
