"""adding history table

Revision ID: 91076b96b601
Revises: 5398807e0f9b
Create Date: 2017-05-22 15:04:37.711499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91076b96b601'
down_revision = '5398807e0f9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('birth_city', sa.Text(), nullable=True),
    sa.Column('birth_state', sa.Text(), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('histories')
    # ### end Alembic commands ###
