"""empty message

Revision ID: 928abdcda2e7
Revises: e68fcfb152c1
Create Date: 2017-08-29 02:08:36.544719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '928abdcda2e7'
down_revision = 'e68fcfb152c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_first_name_key', 'users', type_='unique')
    op.drop_constraint('users_last_name_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_last_name_key', 'users', ['last_name'])
    op.create_unique_constraint('users_first_name_key', 'users', ['first_name'])
    # ### end Alembic commands ###
